# Generated by Django 3.1.7 on 2021-03-03 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='attendee_limit',
            field=models.IntegerField(default=0, help_text='Max. number of attendees (soft limit). 0 for inf.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='secret',
            name='meeting_limit',
            field=models.IntegerField(default=0, help_text='Max. number of meetings. 0 for inf.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='attendee_limit',
            field=models.IntegerField(default=0, help_text='Max. number of attendees (soft limit). 0 for inf.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='meeting_limit',
            field=models.IntegerField(default=0, help_text='Max. number of meetings. 0 for inf.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
