# Generated by Django 3.1.7 on 2021-03-05 16:31

from django.db import migrations, models
import rest.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_add_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='attendees',
            field=models.IntegerField(default=0, help_text='number of attendees metric'),
        ),
        migrations.AlterField(
            model_name='node',
            name='cpu_load',
            field=models.IntegerField(default=0, help_text='cpu load metric (base 10000)'),
        ),
        migrations.AlterField(
            model_name='node',
            name='domain',
            field=models.CharField(default=rest.models.get_node_domain_default, help_text='node domainname setting', max_length=50),
        ),
        migrations.AlterField(
            model_name='node',
            name='has_errors',
            field=models.BooleanField(default=True, help_text='polling has detected a failure'),
        ),
        migrations.AlterField(
            model_name='node',
            name='maintenance',
            field=models.BooleanField(default=False, help_text='in maintenance setting'),
        ),
        migrations.AlterField(
            model_name='node',
            name='meetings',
            field=models.IntegerField(default=0, help_text='number of meetings metric'),
        ),
        migrations.AlterField(
            model_name='node',
            name='secret',
            field=models.CharField(help_text='BBB API secret setting', max_length=50),
        ),
        migrations.AlterField(
            model_name='node',
            name='slug',
            field=models.CharField(help_text='node hostname setting', max_length=100),
        ),
    ]
