# Generated by Django 3.2 on 2021-04-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_update_node_default_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rest.tenant')),
                ('slide', models.FileField(blank=True, null=True, upload_to='rest.AssetSlide/blob/filename/mimetype')),
                ('slide_filename', models.CharField(blank=True, max_length=250, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='rest.AssetLogo/blob/filename/mimetype')),
            ],
            options={
                'ordering': ['tenant__slug'],
            },
        ),
        migrations.CreateModel(
            name='AssetLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.BinaryField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssetSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.BinaryField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('BLOCK', 'BLOCK'), ('SET', 'SET'), ('OVERRIDE', 'OVERRIDE')], max_length=10)),
                ('parameter', models.CharField(choices=[('allowModsToUnmuteUsers', 'allowModsToUnmuteUsers'), ('bannerColor', 'bannerColor'), ('bannerText', 'bannerText'), ('copyright', 'copyright'), ('duration', 'duration'), ('guestPolicy', 'guestPolicy'), ('lockSettingsDisableCam', 'lockSettingsDisableCam'), ('lockSettingsDisableMic', 'lockSettingsDisableMic'), ('lockSettingsDisablePrivateChat', 'lockSettingsDisablePrivateChat'), ('lockSettingsDisablePublicChat', 'lockSettingsDisablePublicChat'), ('lockSettingsDisableNote', 'lockSettingsDisableNote'), ('lockSettingsHideUserList', 'lockSettingsHideUserList'), ('lockSettingsLockOnJoin', 'lockSettingsLockOnJoin'), ('lockSettingsLockOnJoinConfigurable', 'lockSettingsLockOnJoinConfigurable'), ('lockSettingsLockedLayout', 'lockSettingsLockedLayout'), ('logoutURL', 'logoutURL'), ('maxParticipants', 'maxParticipants'), ('meetingKeepEvents', 'meetingKeepEvents'), ('muteOnStart', 'muteOnStart'), ('webcamsOnlyForModerator', 'webcamsOnlyForModerator')], max_length=64)),
                ('value', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='slide',
        ),
        migrations.AlterField(
            model_name='metric',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(choices=[('attendees', 'Total number of current attendees'), ('listeners', 'Total number of current listeners'), ('voices', 'Total number of current voice participants'), ('videos', 'Total number of current video participants'), ('meetings', 'Total number of running meetings'), ('attendees_total', 'Number of attendees that have joined'), ('meetings_total', 'Number of meetings that have been created'), ('meeting_duration_seconds_count', 'Total number of meeting durations'), ('meeting_duration_seconds_sum', 'Sum of meeting durations'), ('attendee_limit_hits', 'Number of attendee limit hits'), ('meeting_limit_hits', 'Number of meeting limit hits')], max_length=64),
        ),
        migrations.AlterField(
            model_name='metric',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.node'),
        ),
        migrations.AlterField(
            model_name='secretmetricslist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.AddField(
            model_name='parameter',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.tenant'),
        ),
        migrations.AddConstraint(
            model_name='parameter',
            constraint=models.UniqueConstraint(fields=('parameter', 'tenant'), name='unique_parameter'),
        ),
    ]
