# Generated by Django 3.2 on 2021-04-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_update_node_default_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rest.tenant')),
                ('slide', models.BinaryField(editable=True, null=True)),
                ('slide_filename', models.CharField(max_length=250, null=True)),
                ('slide_mime_type', models.CharField(editable=False, max_length=50, null=True)),
                ('logo', models.BinaryField(editable=True, null=True)),
                ('logo_mime_type', models.CharField(editable=False, max_length=50, null=True)),
            ],
            options={
                'ordering': ['tenant__slug'],
            },
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='slide',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
