# Generated by Django 3.2.5 on 2021-07-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_parameter_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCustomCSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.BinaryField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='custom_css',
            field=models.FileField(blank=True, null=True, upload_to='rest.AssetCustomCSS/blob/filename/mimetype'),
        ),
        migrations.AddField(
            model_name='asset',
            name='custom_css_mode',
            field=models.CharField(choices=[('Not using custom css', 'Not using custom css'), ("Set if 'userdata-bbb_custom_style_url' parameter is unset", "Set if 'userdata-bbb_custom_style_url' parameter is unset"), ("Overwrite the 'userdata-bbb_custom_style_url' parameter", "Overwrite the 'userdata-bbb_custom_style_url' parameter")], default=('Not using custom css', 'Not using custom css'), max_length=60),
        ),
    ]
