# Generated by Django 3.2.10 on 2022-03-29 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_alter_parameter_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{2,10}$')]),
        ),
    ]
