# Generated by Django 3.2.10 on 2022-01-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_add_record_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('UNKNOWN', 'Record state is unknown'), ('UPLOADED', 'Record files has been uploaded'), ('RENDERED', 'Record files has been rendered to a video'), ('DELETING', 'Record video will be deleted'), ('DELETED', 'Record files have been deleted')], default='UNKNOWN', max_length=10),
        ),
    ]
