# Generated by Django 3.2.15 on 2022-08-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_alter_parameter_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='rest.AssetLogo/blob/filename/mimetype'),
        ),
    ]
