# Generated by Django 3.2.23 on 2024-05-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_alter_parameter_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='room_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=514),
        ),
        migrations.AlterField(
            model_name='recordset',
            name='meta_meeting_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
