# Generated by Django 3.2.23 on 2024-05-24 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rest.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_rename_meeting_meetingold'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingNew',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.CharField(max_length=100)),
                ('room_name', models.CharField(max_length=256)),
                ('age', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendees', models.SmallIntegerField(default=0)),
                ('end_callback_url', models.URLField(default='')),
                ('listenerCount', models.SmallIntegerField(default=0)),
                ('nonce', models.CharField(default=rest.models.get_nonce, editable=False, max_length=64, unique=True)),
                ('voiceParticipantCount', models.SmallIntegerField(default=0)),
                ('moderatorCount', models.SmallIntegerField(default=0)),
                ('videoCount', models.SmallIntegerField(default=0)),
                ('bbb_origin', models.CharField(default='', max_length=255)),
                ('bbb_origin_server_name', models.CharField(default='', max_length=255)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.node')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.secret')),
            ],
            options={
                'ordering': ['secret__tenant', 'age'],
            },
        ),
        migrations.AddConstraint(
            model_name='meetingnew',
            constraint=models.UniqueConstraint(fields=('id', 'secret'), name='unique_meeting'),
        ),
    ]
