# Generated by Django 3.2.23 on 2024-05-24 13:46

from django.db import migrations, models
import django.db.models.deletion

def migrate_record_set_meetings(apps, schema_editor):
    record_set_class = apps.get_model('rest', 'RecordSet')
    for record_set in record_set_class.objects.all():
        if record_set.meeting:
            record_set.meeting = None
            record_set.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0019_migrate_meeting_data'),
    ]

    operations = [
        migrations.RunPython(migrate_record_set_meetings),
        migrations.AlterField(
            model_name='recordset',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.meetingnew'),
        ),
        migrations.DeleteModel(
            name='MeetingOld',
        ),
        migrations.RenameModel(
            old_name='MeetingNew',
            new_name='Meeting',
        ),
        migrations.AlterField(
            model_name='recordset',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.meeting'),
        ),
    ]
