# Join Parameters
# see https://docs.bigbluebutton.org/admin/customize.html#passing-custom-parameters-to-the-client-on-join for documentation
#
# some join parameters needs settings.yml defined inputs, see
# https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/private/config/settings.yml
# for possible options
ENFORCE_LAYOUT = "enforceLayout"
ERROR_REDIRECT_URL = "errorRedirectUrl"
EXCLUDE_FROM_DASHBOARD = "excludeFromDashboard"
FIRST_NAME = "firstName"
LAST_NAME = "lastName"
ROLE = "role"
USERDATA_BBB_ASK_FOR_FEEDBACK_ON_LOGOUT = "userdata-bbb_ask_for_feedback_on_logout"
USERDATA_BBB_AUTO_JOIN_AUDIO = "userdata-bbb_auto_join_audio"
USERDATA_BBB_AUTO_SHARE_WEBCAM = "userdata-bbb_auto_share_webcam"
USERDATA_BBB_AUTO_SWAP_LAYOUT = "userdata-bbb_auto_swap_layout"
USERDATA_BBB_CLIENT_TITLE = "userdata-bbb_client_title"
USERDATA_BBB_CUSTOM_STYLE = "userdata-bbb_custom_style"
USERDATA_BBB_CUSTOM_STYLE_URL = "userdata-bbb_custom_style_url"
USERDATA_BBB_DEFAULT_LAYOUT = "userdata-bbb_default_layout"
USERDATA_BBB_DISPLAY_BRANDING_AREA = "userdata-bbb_display_branding_area"
USERDATA_BBB_ENABLE_SCREEN_SHARING = "userdata-bbb_enable_screen_sharing"
USERDATA_BBB_ENABLE_VIDEO = "userdata-bbb_enable_video"
USERDATA_BBB_FORCE_RESTORE_PRESENTATION_ON_NEW_EVENTS = "userdata-bbb_force_restore_presentation_on_new_events"
USERDATA_BBB_FORCE_LISTEN_ONLY = "userdata-bbb_force_listen_only"
USERDATA_BBB_FULL_AUDIO_BRIDGE = "userdata-bbb_fullaudio_bridge"
USERDATA_BBB_HIDE_CONTROLS = "userdata-bbb_hide_controls"
USERDATA_BBB_HIDE_NOTIFICATIONS = "userdata-bbb_hide_notifications"
USERDATA_BBB_HIDE_PRESENTATION = "userdata-bbb_hide_presentation"
USERDATA_BBB_HIDE_PRESENTATION_ON_JOIN = "userdata-bbb_hide_presentation_on_join"
USERDATA_BBB_LISTEN_ONLY_MODE = "userdata-bbb_listen_only_mode"
USERDATA_BBB_MIRROR_OWN_WEBCAM = "userdata-bbb_mirror_own_webcam"
USERDATA_BBB_MULTI_USER_PEN_ONLY = "userdata-bbb_multi_user_pen_only"
USERDATA_BBB_MULTI_USER_TOOLS = "userdata-bbb_multi_user_tools"
USERDATA_BBB_OVERRIDE_DEFAULT_LOCALE = "userdata-bbb_override_default_locale"
USERDATA_BBB_PREFER_DARK_THEME = "userdata-bbb_prefer_dark_theme"
USERDATA_BBB_PREFERRED_CAMERA_PROFILE = "userdata-bbb_preferred_camera_profile"
USERDATA_BBB_PRESENTER_TOOLS = "userdata-bbb_presenter_tools"
USERDATA_BBB_RECORD_VIDEO = "userdata-bbb_record_video"
USERDATA_BBB_SHORTCUTS = "userdata-bbb_shortcuts"
USERDATA_BBB_SHOW_PARTICIPANTS_ON_LOGIN = "userdata-bbb_show_participants_on_login"
USERDATA_BBB_SHOW_PUBLIC_CHAT_ON_LOGIN = "userdata-bbb_show_public_chat_on_login"
USERDATA_BBB_SKIP_CHECK_AUDIO = "userdata-bbb_skip_check_audio"
USERDATA_BBB_SKIP_CHECK_AUDIO_ON_FIRST_JOIN = "userdata-bbb_skip_check_audio_on_first_join"
USERDATA_BBB_SKIP_ECHOTEST_IF_PREVIOUS_DEVICE = "userdata-bbb_skip_echotest_if_previous_device"
USERDATA_BBB_SKIP_VIDEO_PREVIEW = "userdata-bbb_skip_video_preview"
USERDATA_BBB_SKIP_VIDEO_PREVIEW_ON_FIRST_JOIN = "userdata-bbb_skip_video_preview_on_first_join"
USERDATA_BBB_OUTSIDE_TOGGLE_RECORDING = "userdata-bbb_outside_toggle_recording"
USERDATA_BBB_OUTSIDE_TOGGLE_SELF_VOICE = "userdata-bbb_outside_toggle_self_voice"
WEBCAM_BACKGROUND_URL = "webcamBackgroundURL"
